Workaround for unresolved ~basic_string symbols
In 32-bit mode these linker error occurred when building with libc++-a:

locale.cpp:(.text._ZNKSt3__120__time_get_c_storageIcE3__xEv+0x64): undefined reference to `std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::~basic_string()'

The reason was that g++ did not inline the destructor for some reason,
but libc++.a did not contain an external version of it.

The workaround is a new libcxx-support library, that for now contains
two modules with explicit template instantiations for std::string and
std::wstring.